service chall
{
    disable         = no
    type            = UNLISTED
    protocol        = tcp
    socket_type     = stream
    flags           = NODELAY
    port            = 3134
    bind            = 0.0.0.0
    wait            = no
    user            = ctf
    server          = /home/ctf/run
    log_type        = FILE /var/log/xinetdlog
    log_on_success  = HOST PID
    log_on_failure  = HOST
    per_source      = 10
    rlimit_cpu      = 20
    rlimit_as       = 128M
    cps             = 25 30
}